### ISSUE TITLE
Error when attempting to show plot

### ISSUE THREAD

**Issue by abigailatsea** [noaa-afsc-mace/MACEReports#25]
I'm not sure this really belongs as an "issue" because it's probably just user error, but here goes!
I tried to use MACEReports::plot_biomass_nums_by_length

I've attached the data I used, and a little mini-script so you can reproduce the error. Let me know if this didn't attach right and I can send as email. 
I couldn't find anything in the help, and I am reluctant to open up the functions in MACEReport lest I mangle them. 

This is the error I kept getting:
**Error in seq.default(0, y_axis_max, y_axis_int) : invalid '(to - from)/by'**

[Test_for_mike.zip](https://github.com/user-attachments/files/16912099/Test_for_mike.zip)

**Comment by mike-levine** [comment]
My bad! That is a classic case of needing to write better documentation. I wrote these functions to take biomass (kg) and numbers (individuals)- this only matters because there's a bunch of code in there to decide the units and distances between ticks based on these values. So if you change your code to do that, as in:

```
MACEReports::plot_biomass_nums_by_length(length_vector = e170$Length, 
                                         biomass_vector = e170$Biomass_tons * 1e3,
                                         numbers_vector = e170$NumbersMillions * 1e6,
                                         cex_label_size = 1.75)
```
You get something like:

![image](https://github.com/user-attachments/assets/0f897a9a-2e30-4696-a513-dfc7f5c59f06)

This seems to match reasonably well with the MasterApp view (in this, I just plot transects 1-16, which I know isn't quite the same as East of 170, so things won't quite be the same):

![image](https://github.com/user-attachments/assets/9cefbbf7-7ffb-48ef-9b21-2ee22750ca2b)

Just to show the data doesn't quite match...

![image](https://github.com/user-attachments/assets/5358ccb3-4455-414a-aba9-6ae3f63893a7)

I'll update the help docs and push shortly, let me know if this sorts out the issue on your end in the meantime!

Sorry about that

**Comment by abigailatsea** [comment]
Worked great, thanks Mike! I figured it was an easy fix!

**Comment by mike-levine** [comment]
Cool! Next time you download the package, the documentation should be a bit better... sorry about that.
